"""
GitHub Integration for Pull Request Creation
"""

from typing import List, Dict
from github import Github
from datetime import datetime


class GitHubPRGenerator:
    """
    Generates GitHub Pull Requests with optimization suggestions.
    """
    
    def __init__(self, repo_name: str, token: str):
        """
        Initialize GitHub PR Generator.
        
        Args:
            repo_name: Repository in format "owner/repo"
            token: GitHub personal access token (requires 'repo' scope)
        
        Raises:
            ValueError: If repo_name is not in correct format
        """
        if '/' not in repo_name or repo_name.count('/') != 1:
            raise ValueError(
                f"Invalid repository name '{repo_name}'. "
                "Expected format: 'owner/repo'"
            )
        
        self.repo_name = repo_name
        try:
            self.github = Github(token)
            self.repo = self.github.get_repo(repo_name)
        except Exception as e:
            raise ValueError(
                f"Failed to access repository '{repo_name}'. "
                f"Ensure the token has 'repo' scope and repository exists. Error: {e}"
            )
    
    def create_pr(self, results: List[Dict], goal: str) -> str:
        """
        Create a pull request with optimization suggestions.
        
        Note: Currently creates a PR with optimization recommendations
        in the description. Actual code changes will be implemented in
        a future version.
        
        Args:
            results: List of optimization results
            goal: Optimization goal (speed, cost, memory)
            
        Returns:
            URL of the created pull request
            
        Raises:
            Exception: If PR creation fails
        """
        try:
            # Create a new branch
            timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
            branch_name = f"codeflash/{goal}-optimization-{timestamp}"
            
            # Get the default branch
            default_branch = self.repo.default_branch
            base_ref = self.repo.get_git_ref(f"heads/{default_branch}")
            
            # Create new branch
            self.repo.create_git_ref(
                ref=f"refs/heads/{branch_name}",
                sha=base_ref.object.sha
            )
            
            # TODO: Commit actual code changes to the branch
            # Currently creates a PR with recommendations only
            
            # Generate PR title and description
            title = self._generate_pr_title(goal, len(results))
            description = self._generate_pr_description(results, goal)
            description += "\n\n---\n**Note:** This PR currently contains recommendations only. "
            description += "Automatic code changes will be implemented in a future version."
            
            # Create pull request
            pr = self.repo.create_pull(
                title=title,
                body=description,
                head=branch_name,
                base=default_branch
            )
            
            return pr.html_url
        except Exception as e:
            raise Exception(
                f"Failed to create pull request: {e}. "
                "Ensure your GitHub token has 'repo' scope and you have write access."
            )
    
    def _generate_pr_title(self, goal: str, count: int) -> str:
        """Generate a descriptive PR title."""
        goal_text = {
            'cost': '💰 Cloud Cost',
            'speed': '⚡ Performance',
            'memory': '🧠 Memory',
        }.get(goal, goal.capitalize())
        
        return f"{goal_text} Optimization - {count} improvements"
    
    def _generate_pr_description(self, results: List[Dict], goal: str) -> str:
        """Generate a detailed PR description."""
        goal_emoji = {
            'cost': '💰',
            'speed': '⚡',
            'memory': '🧠',
        }.get(goal, '🔧')
        
        description = f"""# {goal_emoji} Codeflash {goal.capitalize()} Optimization

This PR was automatically generated by Codeflash, an AI-powered Python performance optimizer.

## 📊 Summary

Found and addressed **{len(results)}** optimization opportunities focused on {goal} optimization.

## 🔍 Optimizations Applied

"""
        
        # Group by file
        by_file = {}
        for result in results:
            file = result['file']
            if file not in by_file:
                by_file[file] = []
            by_file[file].append(result)
        
        # Add file-by-file breakdown
        for file, file_results in by_file.items():
            description += f"\n### 📄 `{file}`\n\n"
            for result in file_results:
                description += f"**Line {result['line']}:** {result['issue']}\n"
                description += f"- **Impact:** {result['impact']}\n"
                description += f"- **💡 Solution:** {result['suggestion']}\n\n"
        
        description += """
## 🎯 Expected Impact

"""
        
        if goal == 'cost':
            description += """- **Reduced cloud costs** through memory optimization and lighter dependencies
- **Faster cold starts** in serverless environments (AWS Lambda, Google Cloud Functions)
- **Lower resource consumption** leading to better cost-efficiency
"""
        elif goal == 'speed':
            description += """- **Improved execution speed** through algorithmic optimizations
- **Better response times** for critical code paths
- **Enhanced user experience** through faster operations
"""
        elif goal == 'memory':
            description += """- **Reduced memory footprint** for better scalability
- **Lower RAM usage** enabling more efficient resource allocation
- **Better performance** on memory-constrained environments
"""
        
        description += """
## 🤖 About Codeflash

Codeflash is an AI-powered Python performance optimizer that automatically identifies and fixes performance bottlenecks in your code.

**Want to customize this PR?** Comment your feedback and Codeflash will refine the suggestions!

---
*Generated by Codeflash v0.1.0*
"""
        
        return description
